### ISSUE TITLE
duplicate entries for Atlas PH/ORP feeds

### ISSUE THREAD

**Issue by johnny2678** [rstrouse/relayEquipmentManager#29]
![image](https://user-images.githubusercontent.com/8219743/153113674-3589718b-0844-420c-8378-f09a020ccb13.png)

I cleared out a bunch (10+) of dupes a week ago and they are starting to creep back in.  Wish I could provide more info on how to repeat but not sure when they show up.  Guessing on app restart?

Let me know what other info I can provide.

renamed to .txt
[controllerConfig.txt](https://github.com/rstrouse/relayEquipmentManager/files/8029060/controllerConfig.txt)

edit: this seems harmless as far as I can tell.  no other odd behavior that I can trace back to this.

**Comment by rstrouse** [comment]
Can I get a copy of your poolConfig.json from njsPC.  It appears that there is an invalid feed id in there.

**Comment by johnny2678** [comment]
sure thing.  Let me know if I can provide anything else.
[poolConfig.txt](https://github.com/rstrouse/relayEquipmentManager/files/8056113/poolConfig.txt)

**Comment by rstrouse** [comment]
Go ahead and pull njsPC and REM.  You will need to clean up your duplicates but from then on it should not re-create them.   

Part of the issue is that there were some invalid identifiers for the feeds that would fool njsPC.  When REM starts it will remove feeds with invalid ids but it really shouldn't be cleaning up the duplicates.  You will need to go into REM and delete the duplicate feeds.

**Comment by johnny2678** [comment]
Sure thing. Thanks for looking into this.

**Comment by rstrouse** [comment]
If you are still receiving duplicates after the fix open another issue.
